[camera]

extrinsic = [
[1.0, 0.0, 0.0, 0.0],
[0.0, 1.0, 0.0, 0.0],
[0.0, 0.0, 1.0, 0.0],
[0.0, 0.0, 0.0, 1.0]
]

fov = 90.0
width = 800
height = 800

[[hittable]]
type = "triangle"
a = [-1.0, 1.0, -2.0]
b = [0.0, -1.0, -2.0]
c = [1.0, 1.0, -2.0]
n_a = [0.0, 0.0, 1.0]
n_b = [0.0, 0.0, 1.0]
n_c = [0.0, 0.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
k_a = 0.1
k_d = 0.8
k_s = 0.1
sh = 1.0

[[light_source]]
position = [0.0, 0.0, 0.0]
intensity = 1.0